title: AHB-Lite Multi-Layer Switch
description: Parameterised AHB-Lite Multi-layer Interconnect Switch

theme: jekyll-theme-dinky
show_downloads: true
show_license: true
license: Non-Commercial License

url: https://roalogic.github.io
baseurl: /ahb3lite_interconnect

include:
  - _pages                  # Non-datasheet GH Pages

exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - "*.graffle"             # Original Omnigraffle sources
  - "*.sh"                  # Ignore any scripts
  - "/assets/img/*.pdf"     # PDF images used for PDF Datasheet 
  - "/assets/img/*.eps"     # EPS images used for PDF Datasheet
  - build                   # Temp build folder for PDF Datasheet
  - markdown                # Markdown Datasheet generation scripts
  - pkg                     # PDF Datasheet layout definition
  - tex                     # Original source texfiles
  - Gemfile
  - Gemfile.lock

defaults:
  # _pages
  - scope:
      path    : ""
      type    : pages
    values:
      layout  : roalogic
      author  : Roa Logic
